name: Tawal

on:
  push:
    branches:
      - main
    paths:
      - 'src/code/**'

  workflow_dispatch:
    inputs:
      description:
        description: 'Testing'
        required: true
        type: string

      env:
        description: 'Choose environment'
        required: true
        type: choice
        options:
          - prod
          - dev
          - QA

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show selected environment
        run: |
          echo "Environment: ${{ inputs.env }}"
          echo "Description: ${{ inputs.description }}"
